import Head from "next/head";
import dynamic from "next/dynamic";

//components
const CartPage = dynamic(() => import("../components/CartPage"));
const Menu = dynamic(() => import("../components/Menu"));
const Header = dynamic(() => import("../components/Header"));

//config & firebase
import { loadStripe } from "@stripe/stripe-js";
import { Elements } from "@stripe/react-stripe-js";
import { publishkey } from "../config/stripe";

//redux
import { useSelector } from "react-redux";
import { selectmenuIsOpen } from "../features/menuSlice";
import { selectUser } from "../features/userSlice";
import { selectDarkmode } from "../features/darkmodeSlice";

function Cart() {
  const darkMode = useSelector(selectDarkmode);
  const promise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISH_KEY);
  const MenuNav = useSelector(selectmenuIsOpen);
  const user = useSelector(selectUser);

  console.log("promise", promise);

  return (
    <div>
      <Head>
        <title>ZH Ecommerce - {user?.displayName} Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div
        className={`flex flex-col w-full min-h-screen items-center justify-center ${
          darkMode ? "bg-gray-800" : "bg-gray-100"
        }
    `}
      >
        <Elements stripe={promise}>
          <CartPage />
        </Elements>
        {MenuNav && <Menu />}
      </div>
    </div>
  );
}

export default Cart;
