import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import Banner from "../components/Banner";
import Header from "../components/Header";
import Menu from "../components/Menu";
import ProductFeeds from "../components/ProductFeeds";
import db, { auth } from "../config/firebase";
import { addProducts } from "../features/cartSlice";
import { selectDarkmode } from "../features/darkmodeSlice";
import { selectmenuIsOpen } from "../features/menuSlice";
import { login, selectUser } from "../features/userSlice";

export default function Home({ products }) {
  const dispatch = useDispatch();
  const darkMode = useSelector(selectDarkmode);
  const MenuNav = useSelector(selectmenuIsOpen);
  const user = useSelector(selectUser);

  console.log(" products", products);

  useEffect(() => {
    auth.onAuthStateChanged((user) => {
      if (user) {
        dispatch(
          login({
            displayName: user.displayName,
            email: user.email,
            photoUrl: user.photoURL,
            uid: user.uid,
          })
        );
      }
    });
  }, [user]);

  useEffect(() => {
    dispatch(addProducts(products));
  }, [products]);

  return (
    <div className={`${darkMode ? "bg-gray-800" : "bg-gray-100"}`}>
      <Head>
        <title>Zong Hong Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header products={products} />
      <main className="mx-auto max-w-screen">
        <Banner />

        <ProductFeeds products={products} />
      </main>
      {MenuNav && <Menu />}
    </div>
  );
}

export async function getServerSideProps(context) {
  const ref = db.collection("products");

  const productRes = await ref.get();
  const products = productRes.docs.map((product) => ({
    id: product.id,
    ...product.data(),
  }));

  return {
    props: {
      products: products,
    },
  };
}
